print('Please enter the following information:\n')
first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone = input('Phone number: ')
job_title = input('Job title: ')
id_number = input('ID Number: ')

print()
print('The ID Card is:')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()}')
print(job_title.title())
print(f'ID: {id_number}')
print()
print(email.lower())
print(phone)
print('----------------------------------------')
