print('Please enter the following information:\n')
first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone = input('Phone number: ')
job_title = input('Job title: ')
id_number = input('ID Number: ')

hair_color = input('Hair color: ')
eye_color = input('Eye color: ')
start_month = input('Starting month: ')
training_completed = input('Training completed (Yes/No): ')

print()
print('The ID Card is:')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()}')
print(job_title.title())
print(f'ID: {id_number}')
print()
print(email.lower())
print(phone)
print()
print(f'Hair: {hair_color.capitalize():15} Eyes: {eye_color.capitalize()}')
print(f'Month: {start_month.capitalize():14} Training: {training_completed.capitalize()}')
print('----------------------------------------')
